version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server:18.14.17
    volumes:
      - .env/data:/var/lib/clickhouse/data

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    ports:
      - 9000:9000
      - 8123:8123